### PR TITLE
Version 0.0.2

### PR DESCRIPTION
**Pull request by rapgenic**
Update to version 0.0.2 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by marimeireles** [comment]
Awesome! :)
If you can tag a new version on the repo would be ideal!

**Comment by rapgenic** [comment]
Done! If you want I can try updating the feedstock as well and open a PR for you to check

**Comment by marimeireles** [comment]
We can use this PR =)
No need to open a new one

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by marimeireles** [comment]
Cool! :)
Thanks for this @rapgenic, merging it!

**Pull request merged**
