### PR TITLE
Dev build

### PR DESCRIPTION
**Pull request by rapgenic**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by rapgenic** [comment]
@marimeireles quick ping here, I'm trying to add development builds for testing the conda packages for the new kernel dev version (especially in binder). 

This should not impact at all the main packages.

As per the [knowledge base](https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds) I've changed the channel and the version and I'm merging this to the dev branch. 

Since you've created this recipe I wanted to tell you before merging, in case you have some reason not to go forward with this or in case I've made some obvious error.

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by SylvainCorlay** [comment]
Closing as outdated !

**Pull request closed without merging**
