### PR TITLE
Add osx/arm64 build platform

### PR DESCRIPTION
**Pull request by rapgenic**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See jupyter-xeus/xeus-octave#101.

### CODE REVIEW

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by rapgenic** [comment]
@conda-forge-admin, please rerender

**Comment by rapgenic** [comment]
@AntoinePrv, this adds the `osx-arm64` build platform. If you're ok with this PR I'll merge it

**Review by AntoinePrv — APPROVED** [review]
Thanks!

**Pull request merged**
